### ISSUE TITLE
The SonarQube SCM Stats Plugin is not working on SonarQube Version 5.6

### ISSUE THREAD

**Issue by ptedeschi** [SonarQubeCommunity/sonar-scm-stats#12]
Several posts commented that the sonar-scm-stats works only on < 5.1.2 (LTS).
I tried it with the 5.6 version and the services doesn't starts.
Is there any special technical reason to not evolve the code to make it compatible with the newer versions? Some feature that has gone or something like that?

The plugin is so useful that it is a shame not seeing it working with the latest versions

If you have any ideia what need to be changed I can try fix it.

**Comment by petemounce** [comment]
I just experienced this too - My server now fails to start if the plugin is installed.

**Comment by ptedeschi** [comment]
Exactly... There is an IllegalStateException during Scm Stats plugin load caused by java.lang.NoClassDefFoundError: org/sonar/api/charts/AbstractChart.

I investigated and the AbstractChart was deprecated in 4.5.1 and removed on 5.4.
It was replaced by Javascript charts

**Comment by ptedeschi** [comment]
I solved the problem regarding JFreeChart dependency and could run the instance of sonarqube server BUT when I tried to analyze a project, a new exception occurred:

Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.sonar.plugins.scmstats.MavenScmConfiguration has unsatisfied dependency 'class org.apache.maven.project.MavenProject' for constructor 'public org.sonar.plugins.scmstats.MavenScmConfiguration(org.apache.maven.project.MavenProject)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@619bfe29:215<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@41ab013:220<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@52b1beb6:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@264c5d07:32<|

This plugin is so tied with older versions of sonarqube that it need to be rewritten from scratch. It is a pity!
